# Site settings
title: Homepage of Corentin Lapeyre
email: corentin.lapeyre@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Homepage of Corentin Lapeyre, postdoctoral fellow in numerical
  simulation of combustion physics at CERFACS, Toulouse France
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://clapeyre.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Markdown Processors
kramdown:
  input: GFM
  hard_wrap: false

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: lapeyre@cerfacs.fr
  facebook: corentin.lapeyre
  flickr:
  github: clapeyre
  instagram:
  linkedin: corentinlapeyre
  pinterest:
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: c_lapeyre
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: user/MrAspleet # channel/<your_long_string> or user/<user-name>
  googleplus: +CorentinLapeyre # anything in your profile username that comes after plus.google.com/

